### ISSUE TITLE
Marerittet

### ISSUE THREAD

**Issue by madorian** [odinuge/nrk-tv-downloader#13]
Hi, 

Trying to download, but it's not working:

./nrk-tv-downloader.sh "https://tv.nrk.no/serie/marerittet/FUHA02002089/sesong-1/episode-1"
Downloading ""
 - Tv program is not available:

**Comment by greddost** [comment]
I have been using this great script for quite some time, but recently nrk made some changes so it's not working like it should, was just about to file a issue myself

**Comment by odinuge** [comment]
Thanks @madorian 

@greddost is right. They have made some recent changes, breaking this script.. :-1: 

I guess it is just a simple fix, and will look at it later today (or tomorrow).

Nice to hear people are using the script, and will try to fix it as quick as possible.

**Comment by odinuge** [comment]
Hi,

Feel free to look at #15, as it should fix the problem.

To test it, checkout the `dev` branch, and then pull the new changes;
```
git checkout dev
git pull
./nrk-tv-downloader.sh "yourstuff"
```

**Comment by ianrobrien** [comment]
I was having this issue too and it looks fixed in `dev`. Tusen takk skal du ha!

**Comment by Eightyplus** [comment]
I'm having the same issue and dev branch did not fix it. I'm using mac, seems like a grep is failing on this platform.
```
./nrk-tv-downloader.sh "mystuff"
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
Downloading ""
 - Tv program is not available: 
```

**Comment by eithe** [comment]
@Eightyplus The issue with grep is that the -P flag is not suppored in the BSD grep that comes with macOS.

**Comment by odinuge** [comment]
Looks like you are right @eithe! I have no mac (or other bsd platorm) to test with...

I'll look on to another alternative, i guess gawk will be the easiest solution.

**Comment by eithe** [comment]
@odinuge Sure, but I would advice to support `awk` on macOS instead of `gawk` as the latter doesn't come included.

PS: Should also be possible to rewrite those perl lines quite easily:
`echo https://nrk.no/serie/test | perl -nle 'print $& if m{/serie/\K[^/]+}'`
(instead of your `grep -o -P "/serie/\K[^/]+"`)

**Comment by odinuge** [comment]
@eithe Sure, using perl is a solution, but at the moment it would require rewriting a bit of code (including tt-to-subrip). But if someone would like to do it, feel free to send a PR. :+1:

I don't really know, but i guess getting `gawk` is quite easy?

Pushed a (hopefully) working version to dev, using `gawk`.

**Comment by Eightyplus** [comment]
Most of these regular expression are not very saying and they can be implemented numerous ways shell. why not `sed -E "s/.*([A-Z]{4}[0-9]{8}).*/\1/"`?

I would suggest creating good function names to describe what the regex is actually doing.

**Comment by odinuge** [comment]
Yes, using sed is a nice and simple solution that everyone can live with (both mac and linux users). I can try to adapt the gawk-specific stuff to sed, and try to test with `nawk` (the one shipped with macOS).

This whole project is based purely on html- and json-parsing using regex in awk. Using regex for that, will never result in expressions. So better documentation is on the todo-list.

I am thinking about rewriting it in golang instead. Mostly because it is a _"proper"_ programming language, and because shipping and cross compiling is extremely easy.

**Comment by Eightyplus** [comment]
created PR

**Comment by Eightyplus** [comment]
https://github.com/odinuge/nrk-tv-downloader/pull/16

**Comment by madorian** [comment]
I'm downloading Lykkelandet; works great;)

./nrk-tv-downloader.sh https://tv.nrk.no/serie/brennpunkt/mddp11000617/18-04-2017

Tusen hjertelig takk;)
